### ISSUE TITLE
AttributeError: module 'common_def' has no attribute 'calc_output_shape'

### ISSUE THREAD

**Issue by kobuworks** [yas-sim/pyopenvino#1]
Hi Yas-sim san,
thanks for sharing your great project.

FYI:

test_pyopenvino.py
`AttributeError: module 'common_def' has no attribute 'calc_output_shape'
`

error occured on both
 Ubuntu20.04 @ Core-i KL
 Windows10 @ Core-i TGL

thanks,
BR/Kobu

**Comment by yas-sim** [comment]
Kobu-san,

Thank you for the report. It was a bug and has already been fixed. Please run 'git pull' and give it a try.

Regards,
yas-sim

**Comment by yas-sim** [comment]
I think the issue has been resolved. Now close the case.
